---
- name: Copy Laravel Config file
  become: true 
  copy:
    src: files/laravel.conf 
    dest: /etc/apache2/sites-available/
  
- name: "Enable Apache rewrite module and activate the Laravel virtual host"
  become: true
  shell: |
    a2enmod rewrite
    a2ensite laravel.conf
  notify:
    - Restart Apache2

- name: Configuring PHP
  lineinfile:
      path: /etc/php/8.1/apache2/php.ini
      regexp: '^cgi.fix_pathinfo=0'
      line: 'cgi.fix_pathinfo=1'
      backup: yes
  notify:
    - Restart Apache2

- name: "Copy .env file to laravel app directory"
  copy:
    src: files/.env
    dest: /var/www/html/laravel-realworld-example-app/



- name: Install all dependencies with composer
  community.general.composer:
    command: install 
    working_dir: /var/www/html/laravel-realworld-example-app 
    arguments: --no-dev
  environment:
    COMPOSER_ALLOW_SUPERUSER: 1

- name: Updating the Composer
  community.general.composer:
    command: require 
    arguments: fakerphp/faker
    working_dir: /var/www/html/laravel-realworld-example-app 
  environment:
      COMPOSER_ALLOW_SUPERUSER: 1

- name: Updating the Composer Previously Installed
  community.general.composer:
    command: update 
    working_dir: /var/www/html/laravel-realworld-example-app 
  environment:
      COMPOSER_ALLOW_SUPERUSER: 1     

- name: Give required permissions to laravel app folders
  become: true
  file:
    path: "{{item}}"
    mode: "777"
    recurse: yes
  with_items:
    - /var/www/html/laravel-realworld-example-app
    - /var/www/html/laravel-realworld-example-app/storage
    - /var/www/html/laravel-realworld-example-app/bootstrap/cache

- name: Set Ownership
  become: true
  file:
    path: "{{item}}"
    owner: www-data
    recurse: true
  with_items:
    - /var/www/html/laravel-realworld-example-app

- name: Complete Laravel Installation
  become: true
  command: php artisan key:generate
  args:
    chdir: /var/www/html/laravel-realworld-example-app

- name: Change the laravel routes file
  copy:
    src: files/web.php
    dest: /var/www/html/laravel-realworld-example-app/routes/web.php

- name: App Configuration
  become: true
  shell: |
    php artisan config:cache
    a2dissite 000-default.conf
    rm /etc/apache2/sites-available/000-default.conf
    a2ensite laravel.conf
    php artisan migrate --seed

  args:
    chdir: /var/www/html/laravel-realworld-example-app
    
  notify:
    - Restart Apache2  

